name: Accodex
favicon: null
layout_spectrum: 0.9902
typography_spectrum: 0.845328576862812
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#45a1ee'
    - '#fbffff'
    - '#d4f2ff'
    - '#6eabdd'
    - '#bee0f2'
  brandStrength: 0.658250586129725
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
