name: Accodex
favicon: null
layout_spectrum: 0.25879
typography_spectrum: 0.845328576862812
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.658250586129725
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
